security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        formateur_provider:
            entity:
                class: App\Entity\Formateur
                property: Email
        client_provider:
            entity:
                class: App\Entity\Client
                property: email
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
        chain_provider:
            chain: 
                providers: [formateur_provider, client_provider, admin_provider]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: app_home
            logout:
                path: logout
                target: login
    access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/appel_de_fonds, roles: [ROLE_CLIENT, ROLE_ADMIN] }
    - { path: ^/projet, roles: [ROLE_FORMATEUR, ROLE_ADMIN] }
    - { path: ^/session_formation, roles: ROLE_FORMATEUR }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 4 # Lowest possible value for bcrypt
            time_cost: 3 # Lowest possible value for argon
            memory_cost: 10 # Lowest possible value for argon